sonar.projectKey=GeorgesAlkhouri_sealbreak
sonar.organization=georgesalkhouri
sonar.projectName=Sealbreak
sonar.sources=Sealbreak
sonar.tests=Tests
sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=**/*
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
